// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Address
{
    public int Id { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public int HouseNumber { get; set; }

    public string AdditionalObservation { get; set; }

}